name: Rust

on:
	push:
		branches: ['master, 'dev']
	pull_request:
		branches: ['master, 'dev']

env:
	CARGO_TERM_COLOR: always

jobs:
	build:
		runs-on: ubuntu-latest

		container:
			image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest

		steps:
		- uses: actions/checkout@v4
		- uses: actions-rs/toolchain@v1
		  with:
				profile: minimal
				toolchain: stable
		- name: Clippy
		  run: cargo clippy --all-targets --all-features -- --deny warnings -D clippy::all -D clippy::pedantic -D clippy::nursery
		- name: Build
		  run: cargo build --verbose
		- name: Run tests
		  run: cargo test --verbose
